### ISSUE TITLE
Older versions of the Halifax app no longer work and have been blocked by Halifax

### ISSUE THREAD

**Issue by steve51184** [jcul/BankingHideRoot#9]
Most of us have stayed on an older version of the Halifax app (v6 for most of us) but with the new Halifax v11 they seem to have blocked older versions of the app so could the creator of this mod PLEASE update it to work with the new v11? You could even make it a paid app we'll all buy it :)

**Comment by Overseergti** [comment]
This app isn't even on the Xposed Repo anymore :-(

I'd gladly pay for an updated version that works with Lloyds.

**Comment by steve51184** [comment]
That's two people willing  to pay in just 20mins :)

**Comment by jcul** [comment]
Hi Steve, I'll try have a look into it this week. I actually rooted my current phone and installed the Halifax app a while back with the intention of working on it, but bizarrely it worked fine. Will dig out my old phone and see what I can do.

**Comment by steve51184** [comment]
Thank you I'd really appreciate it :)

**Comment by jcul** [comment]
Had a quick look at the new app tonight guys, it's blocked for me on my old phone, so I can reproduce it anyway. It's not a trivial change, so looks like it will take a bit of work.
Going to try do some more on it this weekend if I can.

**Comment by steve51184** [comment]
Thanks for the work so far sounds promising :)

**Comment by john453** [comment]
indeed, my Lloyds bank app v6 also stopped working too, updated the app to v8 and that version is no longer supported and ofcourse v11 does not work as already mentioned.

Does anyone know if this version - 

ie.jackculhane.haliphaxhideroot_v4_86f750_0.apk

works with v9 or v10 of the halifax or lloyds app?

Also can someone who has it pls upload somewhere pls as cant find it anywhere to test myself.

Thanks for all the hard work jcul ...we appreciate you :)

**Comment by jcul** [comment]
Did some work on the v11 today, it's definitely a bit trickier than before. I think it will take a few more evenings, but making some progress with it.

**Comment by steve51184** [comment]
Excellent! Sounds good! :)

**Comment by steve51184** [comment]
Very strange I tried to install the Halifax and Lloyd's banking apps last week and they both worked fine on my rooted device yet today they both detected root and disabled/signed me out 

Really weird that they both worked for a week then stopped again at the same time

**Comment by steve51184** [comment]
Hey bud no word in 2 months how's things going?

**Comment by Overseergti** [comment]
The Lloyds app is working for me now.  I'm running Android 6.0.1 (MM) with systemless root by Chainfire.  I'm also running Xposed, but not had the app throw me out like it did previously.

**Comment by steve51184** [comment]
yeah both Halifax and Lloyd's both work.. For a random amount of time..
Then it kicks you out and makes you re-register... I found out it does it
mostly when I sent money to someone.. But again I just need to re-register
but gets quite annoying :(

**Comment by john453** [comment]
so steve51184, can we help test this version that works but kicks you out randomly then :)

**Comment by steve51184** [comment]
sure it's the latest version

**Comment by john453** [comment]
thanks steve51184

**Comment by steve51184** [comment]
Halifax and Lloyd's V14 both totally block's you again no way around it please help us :(

**Comment by Overseergti** [comment]
Yep, even with Systemless root V14 not working :-(

**Comment by steve51184** [comment]
Any update on this? 9 months ago I made this topic.. Is the project dead?

**Comment by jcul** [comment]
Hi guys, sorry it's been so long since I posted an update to this.
I'm afraid I don't have a halifax account anymore, and don't live in the UK, so it's not possible for me to do any more work on it.
On top of this I received a take down notice for the module on the xposed repo.

The app has changed so much since I originally wrote it that the old code isn't really of any relevance anyway.

**Comment by jcul** [comment]
Hey Steve,
Ya I'm afraid so, like I said it's not possible for me to continue to work on it.
Also I just don't have the time to maintain it to follow releases from the apps, essentially every time a new version is released, it could mean re-writing this module.

It's a shame these banks don't allow users to essentially have admin access on their devices, though I can see the rationale.
Jack
